### ISSUE TITLE
Schema.org rich data for buildings

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#1]
Rich data snippets should be implemented already on the building page. After the staging server is set up, use Google's rich data testing tool to verify that the data snippets are being parsed correctly.

**Comment by gopperman** [comment]
Depends on #2

**Comment by gopperman** [comment]
Make sure rich data is pushed

**Comment by gopperman** [comment]
https://github.com/WheatonCollege/map/commit/9e4488d6e4cd4019d918fa2b071a504268f4389d

**Comment by scottsousa** [comment]
Data/Properties were updated in: https://github.com/WheatonCollege/map/commit/bf61b57c6e232664be42c3205ac733fa74c1e882

@gopperman 

According to the [Schema.org openingHours](http://schema.org/openingHours) documentation, we need to output this data using a 24 hour timestamp (9:00-16:00) rather than 12 hour timestamps (9am-4pm).

We may have to modify the ACF fields for hours to account for this, or parse this data prior to outputting the rich data value to calculate the correct timestamp.

**Comment by gopperman** [comment]
We can probably "require" the data to be input in 24h format

**Comment by scottsousa** [comment]
I'm going to close this issue for the time being. We're not outputting hours for locations at this time so as of https://github.com/WheatonCollege/map/commit/effd30a7250d179affe84adeb7db324dc120d442 all Schema.org data should be in place.
