### ISSUE TITLE
Implement image gallery lightbox javascript/css for building page

### ISSUE THREAD

**Issue by gopperman** [WheatonCollege/map#12]

**Comment by scottsousa** [comment]
@gopperman Could you take a look at the staging server when you get a chance and let me know what you think of the lightbox implementation?

I found a [library](https://github.com/ashleydw/lightbox) that I've implemented. Bootstrap does contain modal functionality, but it's not really setup for image galleries from what I've found in my research.

The lightbox implementation doesn't quite match the design mock-up, which is why I wanted to have you take a look at it. There are other options/libraries that we might be able to use, but not all of the support an image caption out of the box.

**Comment by scottsousa** [comment]
See https://github.com/WheatonCollege/map/commit/3fa6bb7426fbd8bd34aa7be764cf428df963287a

**Comment by gopperman** [comment]
Looks good, but aesthetically needs to look like Suz's designs. Great job so far!

**Comment by scottsousa** [comment]
@gopperman Do you have any insight as to whether or not the lightbox logic is supposed to function on tablets/phones? As of right now the "View Larger" button is not displayed on viewports with widths less than 768px.

I'm trying to determine whether or not we'll have to add variable height functionality on the lightbox logic for tablets (or other wide-screen devices) viewing the site in landscape mode.

**Comment by gopperman** [comment]
Not for less than 768, no. I don't think it's meaningful until the images break out into the two-column layout, if that makes sense.

**Comment by scottsousa** [comment]
@gopperman Thanks for the info. I agree as well (it doesn't make much sense on smaller devices because the images can't get much larger).

The only issue that I think we need to address is those "wide-screen" devices. Here's what happens on a Google Nexus 7 tablet:

![image](https://cloud.githubusercontent.com/assets/5098743/8188240/8d251c1e-1422-11e5-9473-066cc538c906.png)
![image](https://cloud.githubusercontent.com/assets/5098743/8188243/906265e4-1422-11e5-8112-ed3b6dd464be.png)

There is vertical scrolling due to the height of the lightbox modal.

**Comment by scottsousa** [comment]
@gopperman I also feel that we may need to implement a "close" button on the lightbox as end-users might think they are "stuck" viewing photos. There is no close button in the design mock-up provided.

You can currently click on the overlay to close the lightbox, but I'm not sure they will know that is possible.

Thoughts?

**Comment by gopperman** [comment]
I'm going to defer to @capaddock here. I'm inclined to agree with you,
though.

**Comment by scottsousa** [comment]
In https://github.com/WheatonCollege/map/commit/9b4c3b0b47b5851739547cf57301c2af98b4cdc8 the lightbox modal now matches the design mock-up.

**Comment by capaddock** [comment]
Agreed.
